dataset:
  name: ravdess
  root_dir: ./data/RAVDESS

audio:
  sample_rate: 16000
  max_duration: 6.0
  normalize: true

# ssl:
#   model_type: wavlm
#   model_name: microsoft/wavlm-base-plus
#   layer: mean_last4
#   device: cpu
#   cache_dir: ./.cache/huggingface

# output:
#   feature_dir: ./features/ravdess_wavlm_mean_last4
#   save_format: pt
#   overwrite: false


ssl:
  model_type: emotion2vec
  model_name: emotion2vec/emotion2vec_plus_seed
  device: cpu
  cache_dir: ./.cache/huggingface

output:
  feature_dir: ./features/ravdess_emotion2vec
  save_format: pt
  overwrite: false